### PR TITLE
Vite2

### PR DESCRIPTION
**Pull request by cquiroz**
This is a bit of an experiment to setup vite2. I'm quite happy with the results. we can do `SmallestModule` in dev mode for faster development cycles while using `FewestModules` in production.

Changes to assets are really fast and HMR works well.

A few drawbacks
* The size of the js is significantly larger though it is not related to vite but rather to this bug: https://github.com/scala-js/scala-js/issues/3893
* For now you need to manually keep the package.json file up to date
* No packtracker support
* No status bar support yet

### CODE REVIEW

**Comment by rpiaggio** [comment]
Nice. Looking forward to using this.

What are the `demo/server.*` files?

**Comment by rpiaggio** [comment]
Also, should all the new files in `docs` be checked?

**Comment by rpiaggio** [comment]
> For now you need to manually keep the package.json file up to date

This doesn't seem to be that big of an issue. It has the same info that was previously in `build.sbt` right?

**Review by rpiaggio — APPROVED** [review]
LGTM

**Comment by cquiroz** [comment]
The `demo/server*` files are a self signed cert for the https server. Otherwise vite generates a new cert every time it starts which is annoying

**Comment by cquiroz** [comment]
Another drawback is that this doesn't let you run test that need npm modules

**Comment by cquiroz** [comment]
About the package.json I already designed and compiled a sbt plugin in my mind. Now it needs to go into code :D

**Pull request merged**
